name: omero
channels:
  - defaults
  - conda-forge
  - ome
dependencies:
  - numpy
  - matplotlib
  - pandas
  - pytables
  - jupyter
  - notebook
  - bqplot
  - imageio
  - scikit-image
  - ipywidgets
  - omero-py
  - nodejs
  - jupyterlab
