name: omero
channels:
  - defaults
  - conda-forge
  - ome
dependencies:
  - pandas
  - numpy
  - matplotlib
  - jupyter
  - notebook
  - pbqplot
  - imageio
  - scikit-image
  - ipywidgets
  - omero-py
